spring.application.name=EmployeeTracker

spring.datasource.url=jdbc:postgresql://localhost:5432/rohan
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=12345678901234567890123456789012
jwt.expiration-ms=3600000   
